apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  name: namespace-scc-operator
  selfLink: /apis/authorization.openshift.io/v1/clusterroles/namespace-scc-operator
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  - namespaces
  - pods
  - replicationcontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - namespaces/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  - services
  verbs:
  - create
- apiGroups:
  - security.openshift.io
  attributeRestrictions: null
  resources:
  - securitycontextconstraints
  verbs:
  - '*'
- apiGroups:
  - "namespacescc.github.com"
  resources:
  - namespacesccs
  verbs:
  - list
  - get
  - watch
